### ISSUE TITLE
Sort by Identity or coverage

### ISSUE THREAD

**Issue by ggnicastro** [desmid/mview#15]
It would be nice if we could sort the alignment by the pid/cov columns, or even by a given position in the alignment.

**Comment by desmid** [comment]
Great idea, thanks - added "-sort" option [7fe4403] and release as v1.66.
From the updated manual:

By default MView outputs sequences in the same order they were read in. You
can change this with the ``-sort`` option::

  -sort cov
  -sort pid
  -sort cov:pid
  -sort pid:cov

to sort the output (descending) by coverage, percent identity, coverage then
percent identity, or percent identity then coverage. Rows that coincide in the
sort retain their original local ordering (ascending row number).

You can change the reference sequence and apply one of these sorts like
this::

  -ref 2 -sort cov:pid

which would compute all the coverage and percent identities with respect to
row 2, then sort by coverage and percent identity placing row 2 first.
