### ISSUE TITLE
mview for PHI-BLAST not working

### ISSUE THREAD

**Issue by intikhab** [desmid/mview#17]
Dear Mview Team,

Using Mview, I was trying to fetch MSA from PHI-BLAST search results. Mview reports no alignments found although there are hits to may input pattern input sequence and target database. It is noted that since BLAST+, PHI-BLAST is available as an option to psiblast executable. Header of my blast results looks like:
PHIBLASTP 2.7.1+

Reference: Stephen F. Altschul, Thomas L. Madden, Alejandro A.
Schaffer, Jinghui Zhang, Zheng Zhang, Webb Miller, and David J.
Lipman (1997), "Gapped BLAST and PSI-BLAST: a new generation of
protein database search programs", Nucleic Acids Res. 25:3389-3402.

Looking at mview help it shows PSI-BLAST is supported from both BLAST+ and BLAST but PHI-BLAST seems to supported in older version of BLAST only.

Is there a way to read PHI-BLAST results to be read by mview?

Many Thanks,

Intikhab

**Comment by desmid** [comment]
Hi Intikhab - please can you attach an example file and I can have a look at it.
It doesn't need to be very big, just enough to demonstrate the problem.
Thanks
nigel

**Comment by desmid** [comment]
Resolved and pushed, will be in next release 1.67 tarball.
