### ISSUE TITLE
Can't output in MSF format

### ISSUE THREAD

**Issue by aadimator** [desmid/mview#20]
When I try to convert a `fasta` file to an `MSF` one, it gets stuck. I've tried outputting into all other formats as well, and they all work as expected, but when I try to use `msf` format, it just keeps on running (in one case, for more than 15 minutes, and then I decided to terminate the program manually). It can read the `msf` file easily, but it can't output that same `msf` file in the `msf` format. 
![image](https://user-images.githubusercontent.com/10383542/86895817-75ef0600-c11e-11ea-9ebc-383ad043dd5d.png)

In the above picture, the program has been executing the last statement for more than 5 minutes, still no visible progress. Can you tell me what the issue might be and what's the possible solution? I want to convert my FASTA formatted alignments to MSF format so I can use the `bali_score` program for scoring.

**Comment by desmid** [comment]
Hi - that's weird - please can you send me an example input file so I can reproduce the error.

**Comment by aadimator** [comment]
There you go. These files are the default files provided in the BaliBase dataset.
[RV11.zip](https://github.com/desmid/mview/files/4891369/RV11.zip)

I'm running this on Windows 10. As you can see from the above picture, other commands work as normal, but for some reason, it can't output into MSF format and gets stuck when I try to do so.

**Comment by desmid** [comment]
I just tried the same command in Windows 10 and it hangs as you describe, while working for other output formats.

Workaround: if I hit the return key while it's waiting, it finishes ok.

Let me know if that solves the immediate problem.

**Comment by aadimator** [comment]
Yup, it did the trick. Thanks for the quick response. I should've been able to figure it out but for some reason, I didn't.

**Comment by desmid** [comment]
Cause of problem identified - affected file was UNIX date call in 'lib/Bio/MView/Convert.pm'

**Comment by desmid** [comment]
Fixed in commit 931eb8.

New version of file can be dropped in to replace 'lib/Bio/MView/Convert.pm'
